import Foundation

/// The technique of the exercises whose movement differs from the general one of their family
/// (a face pull is not a seated row, a dead bug is not a leg raise...). Written to match their
/// demonstration step by step.
extension ExerciseLibrary {
    static func technique(for id: String) -> ExerciseTechnique? { techniques[id] }

    private static func t(_ start: String, _ steps: [String], _ range: String, _ breathing: String, _ tips: [String],
                          _ mistakes: [String]) -> ExerciseTechnique {
        ExerciseTechnique(start: start, steps: steps, range: range, breathing: breathing, tips: tips, mistakes: mistakes)
    }

    private static let techniques: [String: ExerciseTechnique] = [
        // Chest and legs: variants whose setup differs from their family
        "pec-deck": t("Assis sur la machine, dos plaqué contre le dossier, poignées à hauteur des épaules, bras ouverts sur les côtés, coudes légèrement fléchis.",
                      ["Rapproche les poignées devant la poitrine en arc de cercle.", "Serre les pectoraux une seconde, mains jointes.", "Ouvre lentement jusqu'à sentir l'étirement, sans dépasser la ligne des épaules."],
                      "Des bras ouverts à la ligne des épaules jusqu'aux mains jointes devant la poitrine.", "Expire en fermant, inspire en ouvrant.",
                      ["Règle le siège pour avoir les poignées à hauteur des épaules.", "Garde la même flexion des coudes du début à la fin."],
                      ["Décoller le dos du dossier.", "Pousser avec les bras en pliant les coudes.", "Laisser les charges claquer en ouvrant."]),
        "cable-fly": t("Debout entre les deux poulies hautes, une poignée dans chaque main, un pied en avant, buste légèrement penché, bras ouverts, coudes un peu fléchis.",
                       ["Amène les mains l'une vers l'autre devant le bas de la poitrine en arc de cercle.", "Serre les pectoraux mains jointes.", "Reviens lentement bras ouverts."],
                       "Des bras ouverts dans la ligne des épaules aux mains jointes.", "Expire en fermant, inspire en ouvrant.",
                       ["Coudes fixes, le mouvement vient des épaules.", "Buste stable."],
                       ["Transformer l'écarté en développé.", "Se laisser tirer vers l'arrière par les câbles."]),
        "front-squat": t("Debout, barre posée sur l'avant des épaules contre les clavicules, bras croisés devant (ou prise olympique), coudes hauts, pieds largeur d'épaules.",
                         ["Descends en gardant le buste bien droit et les coudes hauts.", "Genoux dans l'axe des pieds jusqu'aux cuisses parallèles.", "Remonte en poussant dans tout le pied."],
                         "Au moins jusqu'aux cuisses parallèles, buste droit.", "Inspire et gaine en haut, expire en remontant.",
                         ["Coudes hauts pour que la barre ne glisse pas.", "Regard droit devant."],
                         ["Coudes qui tombent.", "Buste qui part en avant.", "Talons qui décollent."]),
        // Back and shoulders
        "dead-hang": t("Suspendu à la barre, mains largeur d'épaules, bras tendus, pieds décollés du sol.",
                       ["Abaisse légèrement les épaules pour les engager.", "Tiens la suspension en respirant calmement.", "Repose les pieds au sol avant de lâcher."],
                       "Bras tendus tout le long : on ne tire pas.", "Respire calmement, sans bloquer.",
                       ["Serre fort la barre.", "Gaine légèrement le ventre."],
                       ["Hausser les épaules jusqu'aux oreilles.", "Se balancer.", "Lâcher la barre d'un coup."]),
        "face-pull": t("Debout face à la poulie haute, corde à hauteur des yeux, bras tendus, un pas en arrière.",
                       ["Tire la corde vers le visage en ouvrant les coudes, hauts et vers l'extérieur.", "Écarte les mains de chaque côté de la tête.", "Reviens bras tendus sous contrôle."],
                       "Des bras tendus jusqu'aux mains à hauteur des oreilles.", "Expire en tirant, inspire en revenant.",
                       ["Coudes au niveau des épaules ou un peu au-dessus.", "Serre les omoplates en fin de mouvement."],
                       ["Tirer avec le dos en se penchant en arrière.", "Coudes qui tombent le long du corps.", "Charge trop lourde."]),
        "band-pull-apart": t("Debout, bras tendus devant toi à hauteur des épaules, l'élastique dans les mains.",
                             ["Écarte les bras sur les côtés en gardant les coudes tendus.", "Amène l'élastique contre la poitrine.", "Reviens lentement bras devant."],
                             "Jusqu'à l'élastique contre la poitrine, bras dans l'alignement des épaules.", "Expire en écartant, inspire en revenant.",
                             ["Serre les omoplates.", "Épaules basses."],
                             ["Plier les coudes.", "Cambrer le dos.", "Hausser les épaules."]),
        "rear-delt-fly": t("Debout, buste penché presque à l'horizontale, dos plat, genoux fléchis, haltères sous les épaules.",
                           ["Ouvre les bras sur les côtés, coudes légèrement fléchis.", "Monte jusqu'aux bras à hauteur des épaules.", "Redescends lentement."],
                           "Jusqu'aux bras dans l'alignement des épaules.", "Expire en ouvrant, inspire en redescendant.",
                           ["C'est l'arrière de l'épaule qui travaille : charge légère.", "Nuque dans l'alignement du dos."],
                           ["Redresser le buste pour donner de l'élan.", "Tirer les coudes vers l'arrière (ça devient un rowing).", "Dos rond."]),
        "reverse-pec-deck": t("Assis face à la machine, poitrine contre l'appui, bras tendus devant toi sur les poignées à hauteur des épaules.",
                              ["Ouvre les bras vers l'arrière en arc de cercle.", "Va jusqu'aux bras dans l'alignement des épaules.", "Reviens lentement devant."],
                              "Des mains devant toi jusqu'aux bras à l'horizontale sur les côtés.", "Expire en ouvrant, inspire en revenant.",
                              ["Règle le siège : poignées à hauteur des épaules.", "Coudes légèrement fléchis et fixes."],
                              ["Décoller la poitrine de l'appui.", "Hausser les épaules.", "Revenir trop vite."]),
        "straight-arm-pulldown": t("Debout face à la poulie haute, un pas en arrière, buste légèrement penché, bras tendus vers la barre.",
                                   ["Abaisse la barre en arc de cercle jusqu'aux cuisses, bras tendus.", "Serre le dos en bas.", "Remonte lentement à hauteur des yeux."],
                                   "De la barre à hauteur des yeux jusqu'aux cuisses.", "Expire en abaissant, inspire en remontant.",
                                   ["Coudes légèrement fléchis et fixes.", "Le buste ne bouge pas."],
                                   ["Plier les coudes (ça devient un triceps).", "Basculer le buste pour descendre."]),
        "pallof-press": t("Debout de profil à la poulie réglée à hauteur de poitrine, poignée contre le sternum, pieds largeur d'épaules.",
                          ["Pousse la poignée droit devant toi jusqu'aux bras tendus.", "Tiens une à deux secondes sans laisser le buste tourner.", "Ramène la poignée contre la poitrine."],
                          "De la poitrine aux bras tendus devant toi.", "Expire en poussant, respire calmement en tenant.",
                          ["Gaine le ventre et serre les fessiers.", "Fais les deux côtés."],
                          ["Laisser le buste tourner vers la poulie.", "Se pencher.", "Charge trop lourde."]),
        // Arms
        "wrist-curl": t("Assis sur un banc, avant-bras posés sur les cuisses, poignets dans le vide, barre en main paumes vers le haut.",
                        ["Laisse descendre la barre en pliant les poignets.", "Remonte en fléchissant les poignets le plus haut possible.", "Redescends lentement."],
                        "Seuls les poignets bougent, toute l'amplitude confortable.", "Expire en montant, inspire en redescendant.",
                        ["Avant-bras bien posés.", "Charge légère, mouvement lent."],
                        ["Décoller les avant-bras.", "Donner de l'élan avec les épaules."]),
        "concentration-curl": t("Assis au bout d'un banc, jambes écartées, buste penché, l'arrière du bras contre l'intérieur de la cuisse.",
                                ["Plie le coude pour monter l'haltère vers l'épaule.", "Serre en haut.", "Redescends lentement jusqu'au bras tendu."],
                                "Du bras tendu jusqu'à la flexion complète.", "Expire en montant, inspire en redescendant.",
                                ["Le bras reste collé à la cuisse.", "L'autre main en appui sur l'autre cuisse."],
                                ["Bouger le buste.", "Décoller le coude de la cuisse."]),
        "kickback": t("Debout, buste penché presque à l'horizontale, dos plat, bras collés au corps, coudes pliés à 90°.",
                      ["Tends les avant-bras vers l'arrière jusqu'aux bras tendus.", "Marque une seconde.", "Reviens lentement à 90°."],
                      "Du coude plié à 90° jusqu'au bras tendu.", "Expire en tendant, inspire en revenant.",
                      ["Le haut du bras reste immobile, le long du buste.", "Charge légère."],
                      ["Coude qui descend.", "Balancer la charge.", "Dos rond."]),
        "overhead-extension": t("Debout, un haltère tenu à deux mains au-dessus de la tête, bras tendus.",
                                ["Plie les coudes pour descendre l'haltère derrière la tête.", "Tends de nouveau les bras."],
                                "Tant que les épaules restent confortables.", "Inspire en descendant, expire en tendant.",
                                ["Coudes pointés vers le haut, proches de la tête.", "Gaine le ventre pour ne pas cambrer."],
                                ["Coudes qui s'écartent.", "Cambrer le dos."]),
        "bench-dips": t("Dos au banc, mains sur le bord, doigts vers l'avant, jambes allongées, talons au sol.",
                        ["Plie les coudes pour descendre les fesses le long du banc.", "Pousse sur les mains pour remonter bras tendus."],
                        "Jusqu'aux coudes à environ 90°.", "Inspire en descendant, expire en remontant.",
                        ["Fesses près du banc.", "Coudes vers l'arrière, pas sur les côtés."],
                        ["Descendre trop bas.", "Épaules qui montent vers les oreilles."]),
        // Legs and glutes
        "wall-sit": t("Dos plaqué au mur, pieds en avant, écartés largeur de hanches.",
                      ["Glisse le long du mur jusqu'aux cuisses parallèles au sol.", "Genoux au-dessus des chevilles : tiens la position.", "Remonte en glissant contre le mur."],
                      "Cuisses parallèles au sol, position fixe.", "Respire calmement, sans bloquer.",
                      ["Tout le dos contre le mur.", "Poids sur les talons."],
                      ["Genoux qui dépassent les orteils.", "Mains sur les cuisses pour s'aider."]),
        "hack-squat": t("Dos et épaules contre les appuis de la machine, pieds largeur d'épaules sur le plateau.",
                        ["Déverrouille les sécurités.", "Descends en pliant les genoux, le dos glisse le long des rails.", "Pousse dans tout le pied pour remonter."],
                        "Jusqu'aux cuisses parallèles au plateau.", "Inspire en descendant, expire en poussant.",
                        ["Genoux dans l'axe des pieds.", "Bas du dos collé au dossier."],
                        ["Verrouiller les genoux en haut.", "Talons qui décollent.", "Genoux qui rentrent."]),
        "step-up": t("Debout face au banc, haltères le long du corps, un pied posé à plat sur le banc.",
                     ["Pousse sur la jambe posée sur le banc pour monter.", "Ramène l'autre pied à côté, debout sur le banc.", "Redescends sous contrôle, un pied après l'autre."],
                     "Du pied au sol jusqu'à debout sur le banc.", "Expire en montant, inspire en descendant.",
                     ["Pose tout le pied sur le banc.", "Buste droit."],
                     ["Pousser avec la jambe restée au sol.", "Genou qui rentre."]),
        "nordic-curl": t("À genoux sur un tapis, chevilles bloquées sous un appui, corps droit des genoux à la tête.",
                         ["Descends le buste vers l'avant le plus lentement possible, hanches tendues.", "Amortis avec les mains près du sol.", "Repousse légèrement et remonte."],
                         "Aussi bas que tu peux contrôler la descente.", "Inspire en descendant, expire en remontant.",
                         ["Hanches dans l'alignement : on ne casse pas au bassin.", "Progresse petit à petit."],
                         ["Plier les hanches.", "Se laisser tomber."]),
        "single-leg-rdl": t("Debout sur une jambe, genou légèrement fléchi, haltère dans la main opposée.",
                            ["Penche le buste en avant pendant que la jambe libre part vers l'arrière.", "Descends jusqu'au corps à l'horizontale, en « T ».", "Reviens debout en poussant la hanche vers l'avant."],
                            "Jusqu'au buste presque horizontal, dos plat.", "Inspire en descendant, expire en remontant.",
                            ["Bassin face au sol.", "Charge près de la jambe d'appui."],
                            ["Ouvrir la hanche sur le côté.", "Dos rond."]),
        "kb-swing": t("Debout, pieds un peu plus larges que les hanches, kettlebell au sol devant toi.",
                      ["Charnière de hanches : la kettlebell passe entre les jambes.", "Pousse les hanches vers l'avant d'un coup sec.", "La kettlebell monte à hauteur de poitrine, bras tendus, puis redescend en balancier."],
                      "Bras à l'horizontale en haut.", "Expire au coup de hanches.",
                      ["La force vient des hanches, les bras ne font que tenir.", "Serre les fessiers en haut."],
                      ["Squatter au lieu de plier les hanches.", "Lever la kettlebell avec les bras.", "Dos rond en bas."]),
        "glute-bridge": t("Allongé sur le dos, genoux pliés, pieds à plat largeur de hanches, bras le long du corps.",
                          ["Pousse dans les talons pour monter les hanches.", "Serre les fessiers en haut, épaules-hanches-genoux alignés.", "Redescends sous contrôle."],
                          "Jusqu'à l'alignement du buste et des cuisses.", "Expire en montant, inspire en redescendant.",
                          ["Menton rentré.", "Pieds pas trop loin des fesses."],
                          ["Cambrer le bas du dos en haut.", "Pousser sur la pointe des pieds."]),
        "single-leg-bridge": t("Allongé sur le dos, un pied à plat, l'autre jambe tendue dans l'alignement de la cuisse.",
                               ["Pousse dans le talon d'appui pour monter les hanches.", "Garde le bassin de niveau en haut.", "Redescends sous contrôle."],
                               "Jusqu'à l'alignement épaules-hanches-genou.", "Expire en montant, inspire en redescendant.",
                               ["Bassin bien horizontal.", "Fais les deux côtés."],
                               ["Bassin qui bascule d'un côté.", "Cambrer le dos."]),
        "donkey-kick": t("À quatre pattes, mains sous les épaules, genoux sous les hanches, dos plat.",
                         ["Genou plié à 90°, pousse le talon vers le plafond.", "Monte jusqu'à la cuisse dans l'alignement du dos.", "Reviens sans poser le genou."],
                         "Jusqu'à la cuisse à l'horizontale.", "Expire en montant, inspire en revenant.",
                         ["Le bassin reste face au sol.", "Ventre gainé."],
                         ["Cambrer pour monter plus haut.", "Tourner le bassin."]),
        "fire-hydrant": t("À quatre pattes, mains sous les épaules, genoux sous les hanches, dos plat.",
                          ["Lève le genou plié sur le côté.", "Monte jusqu'à la cuisse presque horizontale.", "Redescends lentement."],
                          "Tant que le bassin ne tourne pas.", "Expire en levant, inspire en redescendant.",
                          ["Genou plié à 90° tout le long.", "Épaules et bassin immobiles."],
                          ["Pencher tout le corps de l'autre côté.", "Aller trop vite."]),
        "cable-kickback": t("Debout face à la poulie basse, sangle à la cheville, mains sur la machine, buste légèrement penché.",
                            ["Pousse la jambe tendue vers l'arrière en contractant le fessier.", "Marque une seconde.", "Reviens lentement."],
                            "Jusqu'à la jambe un peu derrière le corps, sans cambrer.", "Expire en poussant, inspire en revenant.",
                            ["Le bassin reste immobile.", "Genou presque tendu."],
                            ["Cambrer le bas du dos.", "Balancer la jambe."]),
        "hip-abduction": t("Assis dans la machine, dos contre le dossier, coussins contre l'extérieur des genoux.",
                           ["Écarte les genoux contre la résistance.", "Marque une seconde en ouverture.", "Reviens lentement."],
                           "Toute l'amplitude confortable.", "Expire en écartant, inspire en revenant.",
                           ["Tiens les poignées pour rester assis.", "Mouvement lent."],
                           ["Laisser claquer les charges.", "Décoller le dos."]),
        "hip-adduction": t("Assis dans la machine, dos contre le dossier, coussins contre l'intérieur des genoux, jambes écartées.",
                           ["Resserre les genoux contre la résistance.", "Marque une seconde genoux joints.", "Rouvre lentement."],
                           "De l'ouverture confortable jusqu'aux genoux joints.", "Expire en serrant, inspire en ouvrant.",
                           ["Tiens les poignées.", "Ouverture sans forcer."],
                           ["Ouvrir trop grand.", "Donner de l'élan."]),
        "seated-calf": t("Assis à la machine, coussin sur le bas des cuisses, avant des pieds sur la marche.",
                         ["Laisse descendre les talons sous la marche.", "Monte sur la pointe des pieds le plus haut possible.", "Redescends lentement."],
                         "Du talon bas jusqu'à la pointe haute.", "Expire en montant, inspire en redescendant.",
                         ["Pause en bas et en haut.", "Genoux à 90°."],
                         ["Rebondir.", "Amplitude trop courte."]),
        "single-calf": t("Debout sur une jambe, l'avant du pied sur une marche, haltère du même côté, l'autre main contre un mur.",
                         ["Laisse descendre le talon sous la marche.", "Monte sur la pointe du pied le plus haut possible.", "Redescends lentement."],
                         "Du talon bas jusqu'à la pointe haute.", "Expire en montant, inspire en redescendant.",
                         ["Jambe d'appui droite sans verrouiller.", "La main ne sert qu'à l'équilibre."],
                         ["Rebondir.", "Pousser avec la main sur le mur."]),
        // Core
        "cable-crunch": t("À genoux face à la poulie haute, la corde tenue de chaque côté de la tête.",
                          ["Enroule le buste vers le sol, coudes vers les cuisses.", "Les hanches restent immobiles.", "Remonte lentement."],
                          "Jusqu'aux coudes près des cuisses.", "Expire en enroulant, inspire en remontant.",
                          ["Ce sont les abdominaux qui tirent, pas les bras.", "Dos qui s'arrondit, hanches fixes."],
                          ["S'asseoir sur les talons pour descendre.", "Tirer avec les bras."]),
        "side-plank": t("Allongé sur le côté, avant-bras au sol, coude sous l'épaule, jambes tendues l'une sur l'autre.",
                        ["Monte les hanches jusqu'à aligner tout le corps.", "Tiens la position.", "Redescends doucement, puis change de côté."],
                        "Corps aligné des chevilles à la tête, position fixe.", "Respire calmement, sans bloquer.",
                        ["Hanches hautes, ne les laisse pas tomber.", "Épaule au-dessus du coude."],
                        ["Hanches qui s'affaissent.", "Buste qui bascule vers l'avant."]),
        "ab-wheel": t("À genoux, mains sur la roue sous les épaules, dos neutre.",
                      ["Roule vers l'avant en allongeant le corps.", "Va aussi loin que tu tiens le dos neutre.", "Reviens en contractant les abdominaux."],
                      "Tant que le bas du dos ne se creuse pas.", "Inspire en avançant, expire en revenant.",
                      ["Fessiers et ventre serrés.", "Progresse en amplitude petit à petit."],
                      ["Creuser le dos.", "Revenir en poussant les fesses vers l'arrière en premier."]),
        "dead-bug": t("Allongé sur le dos, bras tendus vers le plafond, hanches et genoux pliés à 90°.",
                      ["Tends un bras derrière la tête et la jambe opposée près du sol.", "Reviens au centre.", "Change de côté."],
                      "Tant que le bas du dos reste plaqué au sol.", "Expire en tendant, inspire en revenant.",
                      ["Bas du dos collé au sol tout le long.", "Mouvement lent."],
                      ["Creuser le dos.", "Bouger le bras et la jambe du même côté."]),
        "hollow-hold": t("Allongé sur le dos, bras tendus derrière la tête, jambes tendues.",
                         ["Décolle les épaules, les bras et les jambes du sol.", "Bas du dos plaqué : tiens la position en « banane ».", "Repose doucement."],
                         "Bras et jambes juste au-dessus du sol, position fixe.", "Respire calmement, sans bloquer.",
                         ["Plus les jambes sont hautes, plus c'est facile.", "Menton rentré."],
                         ["Creuser le bas du dos.", "Retenir sa respiration."]),
        "back-extension": t("Sur le banc à 45°, hanches sur l'appui, chevilles bloquées sous les rouleaux, corps aligné, bras croisés.",
                            ["Descends le buste vers le sol en pliant les hanches.", "Remonte jusqu'à l'alignement du corps.", "Pas plus haut."],
                            "Du buste vers le sol jusqu'au corps aligné, sans cambrer.", "Inspire en descendant, expire en remontant.",
                            ["Dos plat tout le long.", "Serre les fessiers en remontant."],
                            ["Cambrer en haut.", "Donner de l'élan."]),
        "bird-dog": t("À quatre pattes, mains sous les épaules, genoux sous les hanches, dos plat.",
                      ["Tends un bras devant toi et la jambe opposée derrière.", "Tiens une seconde, le dos immobile.", "Reviens et change de côté."],
                      "Bras et jambe dans l'alignement du dos.", "Expire en tendant, inspire en revenant.",
                      ["Bassin face au sol.", "Mouvement lent."],
                      ["Cambrer le dos.", "Lever la jambe trop haut."]),
        // Full body and cardio
        "burpee": t("Debout, pieds largeur de hanches.",
                    ["Accroupis-toi et pose les mains au sol.", "Saute les pieds en arrière en planche.", "Ramène les pieds sous toi d'un saut.", "Saute vers le haut, bras au-dessus de la tête, et reçois-toi souplement."],
                    "Enchaîne à ton rythme, corps gainé en planche.", "Respire en rythme.",
                    ["Mains à plat sous les épaules en planche.", "Réception sur l'avant du pied, genoux fléchis."],
                    ["Hanches qui s'affaissent en planche.", "Atterrir jambes tendues."]),
        "thruster": t("Debout, barre en position de squat avant, coudes hauts.",
                      ["Descends en squat avant, buste droit.", "Remonte de façon explosive et pousse la barre au-dessus de la tête dans le même élan.", "Ramène la barre aux épaules en descendant dans le squat suivant."],
                      "Du squat aux bras tendus au-dessus de la tête.", "Inspire en descendant, expire en poussant.",
                      ["La poussée des jambes lance la barre.", "Barre au-dessus du milieu du pied."],
                      ["Pousser avec les bras seuls.", "Coudes qui tombent en bas du squat."]),
        "power-clean": t("Barre au sol au-dessus du milieu du pied, dos plat, bras tendus, épaules légèrement devant la barre.",
                         ["Premier tirage : pousse avec les jambes, barre collée aux tibias.", "Extension explosive des hanches, sur la pointe des pieds, haussement d'épaules.", "Passe sous la barre : réception sur l'avant des épaules en squat partiel, coudes hauts.", "Redresse-toi, puis redescends la barre aux hanches et au sol."],
                         "Du sol aux épaules.", "Bloque l'air au départ, expire après la réception.",
                         ["La barre reste près du corps.", "Apprends-le avec un coach, à vide d'abord."],
                         ["Tirer avec les bras trop tôt.", "Dos rond au départ.", "Recevoir la barre bras tendus devant."]),
        "kb-clean": t("Debout, kettlebell entre les pieds, saisie d'une main.",
                      ["Balancier entre les jambes, puis coup de hanches.", "La kettlebell monte près du corps.", "Elle se pose sur l'avant-bras, coude collé au buste, main à hauteur du menton.", "Redescends-la en balancier."],
                      "Des jambes jusqu'à la position de rack.", "Expire au coup de hanches.",
                      ["Tourne la main autour de la poignée pour amortir.", "Coude serré au corps en haut."],
                      ["Laisser la kettlebell frapper l'avant-bras.", "Tirer avec le bras seul."]),
        "turkish-get-up": t("Allongé sur le dos, kettlebell bras tendu vers le plafond, genou du même côté plié, pied au sol.",
                            ["Monte sur le coude opposé, puis sur la main.", "Lève les hanches.", "Passe la jambe tendue sous toi pour poser le genou.", "Redresse le buste, puis lève-toi ; redescends dans l'ordre inverse."],
                            "Du sol à debout, bras toujours tendu vers le plafond.", "Respire à chaque étape.",
                            ["Regarde la kettlebell.", "Commence sans charge pour apprendre les étapes."],
                            ["Plier le bras qui tient la charge.", "Aller trop vite.", "Charger avant de maîtriser."]),
        "wall-ball": t("Debout face au mur à un pas, médecine-ball tenu contre la poitrine.",
                       ["Descends en squat.", "Remonte en poussant et lance le ballon vers la cible.", "Rattrape-le et enchaîne le squat suivant."],
                       "Squat complet, bras tendus au lancer.", "Expire au lancer.",
                       ["Les jambes donnent la force du lancer.", "Coudes sous le ballon."],
                       ["Lancer seulement avec les bras.", "Rattraper le ballon bras tendus et dos cambré."]),
        "battle-ropes": t("Debout face à l'ancrage, genoux fléchis, buste légèrement penché, une corde dans chaque main.",
                          ["Lève et abaisse les bras en alternance.", "Fais onduler les cordes jusqu'à l'ancrage.", "Garde le rythme sur la durée prévue."],
                          "Mouvements amples des bras, des hanches à la poitrine.", "Respire en rythme.",
                          ["Gaine le ventre.", "Reste bas sur les jambes."],
                          ["Se redresser complètement.", "Bloquer sa respiration."]),
        "sled-push": t("Mains sur les montants du traîneau, bras tendus, buste penché vers l'avant.",
                       ["Pousse le sol avec les jambes, à petits pas puissants.", "Garde le dos droit et le buste penché.", "Avance sur la distance prévue."],
                       "Sur la distance ou le temps choisi.", "Respire en rythme.",
                       ["Pousse avec l'avant du pied.", "Bras tendus et fixes."],
                       ["Dos rond.", "Se redresser en poussant."]),
        "bear-crawl": t("À quatre pattes, mains sous les épaules, genoux juste au-dessus du sol.",
                        ["Avance une main et le pied opposé en même temps.", "Puis l'autre main et l'autre pied.", "Garde les genoux bas et le dos plat."],
                        "Sur la distance ou le temps choisi.", "Respire en rythme.",
                        ["Hanches à la hauteur des épaules.", "Petits pas."],
                        ["Hanches trop hautes.", "Genoux qui touchent le sol."]),
        "treadmill": t("Debout au milieu du tapis, regard devant, sans tenir les barres.",
                       ["Démarre doucement, puis règle la vitesse.", "Cours avec une foulée souple, sous le corps.", "Ralentis progressivement avant de t'arrêter."],
                       "Sur la durée ou la distance prévue.", "Respire régulièrement.",
                       ["Reste au centre du tapis.", "Bras détendus, coudes à 90°."],
                       ["S'accrocher aux barres.", "Monter trop vite en vitesse."]),
        "incline-walk": t("Debout sur le tapis réglé en pente, regard devant.",
                          ["Marche à grands pas réguliers.", "Pose le pied à plat et pousse jusqu'aux orteils.", "Ajuste la pente et la vitesse selon la séance."],
                          "Sur la durée prévue.", "Respire régulièrement ; tu dois pouvoir parler.",
                          ["Buste légèrement penché, pas plus.", "Sans tenir les barres si possible."],
                          ["S'accrocher aux barres.", "Pente trop forte dès le départ."]),
        "high-knees": t("Debout, pieds largeur de hanches, bras pliés.",
                        ["Monte un genou à hauteur de hanche.", "Change de jambe rapidement, sur place.", "Les bras accompagnent en rythme."],
                        "Genoux à hauteur de hanches.", "Respire en rythme.",
                        ["Réception sur l'avant du pied.", "Buste droit."],
                        ["Se pencher en arrière.", "Genoux trop bas."]),
        "elliptical": t("Debout sur les pédales, mains sur les poignées mobiles, buste droit.",
                        ["Pédale en mouvement elliptique, pieds à plat.", "Pousse et tire les poignées en rythme avec les jambes.", "Ajuste la résistance selon la séance."],
                        "Sur la durée prévue.", "Respire régulièrement.",
                        ["Talons qui restent sur les pédales.", "Buste droit, sans s'appuyer."],
                        ["Se pencher sur la console.", "Résistance trop forte."]),
        "stair-climber": t("Debout sur les pédales du stepper, mains légèrement posées sur les barres.",
                           ["Pousse une pédale vers le bas pendant que l'autre remonte.", "Alterne à rythme régulier.", "Garde le buste droit."],
                           "Sur la durée prévue, amplitude complète.", "Respire régulièrement.",
                           ["Pose tout le pied sur la pédale.", "Les mains servent à l'équilibre."],
                           ["S'appuyer de tout son poids sur les barres.", "Petits pas rapides sans amplitude."]),
        "jump-rope": t("Debout, corde derrière toi, mains à hauteur des hanches, coudes près du corps.",
                       ["Fais tourner la corde avec les poignets.", "Saute juste assez haut pour la laisser passer.", "Enchaîne à rythme régulier."],
                       "Petits sauts sur l'avant du pied.", "Respire en rythme.",
                       ["Poignets qui tournent, pas les bras.", "Atterrissage souple."],
                       ["Sauter trop haut.", "Atterrir sur les talons."]),
        "jumping-jacks": t("Debout, pieds joints, bras le long du corps.",
                           ["Saute en écartant les pieds et lève les bras au-dessus de la tête.", "Saute pour revenir pieds joints, bras le long du corps.", "Enchaîne à ton rythme."],
                           "Bras au-dessus de la tête, pieds plus larges que les épaules.", "Respire en rythme.",
                           ["Réception sur l'avant du pied.", "Genoux souples."],
                           ["Atterrir jambes tendues.", "Arrondir le dos."]),
        "box-jump": t("Debout face à la boîte, à environ un pas, pieds largeur de hanches.",
                      ["Élan : fléchis les jambes, bras en arrière.", "Saute en lançant les bras vers l'avant.", "Reçois-toi à deux pieds sur la boîte, genoux fléchis, puis redresse-toi.", "Redescends en marchant."],
                      "Hauteur de boîte maîtrisée.", "Expire au saut.",
                      ["Atterrissage silencieux, au centre de la boîte.", "Commence avec une boîte basse."],
                      ["Redescendre en sautant en arrière.", "Genoux qui rentrent à la réception."]),
        "hiit": t("Debout, échauffé, espace dégagé autour de toi.",
                  ["Enchaîne les exercices du circuit à intensité élevée (ici jumping jacks, squats sautés, montées de genoux).", "Récupère entre les blocs selon ta séance.", "Répète le circuit."],
                  "Sur les durées d'effort et de repos prévues.", "Respire en rythme, sans bloquer.",
                  ["La qualité des mouvements avant la vitesse.", "Adapte l'intensité à ton niveau."],
                  ["Négliger l'échauffement.", "Sacrifier la technique en fin de série."]),
        "swimming": t("Allongé sur l'eau sur le ventre, corps aligné, visage dans l'eau.",
                      ["Les bras alternent : l'un tire sous l'eau pendant que l'autre revient au-dessus.", "Les jambes battent en petits mouvements rapides.", "Tourne la tête sur le côté pour respirer."],
                      "Sur la distance ou le temps prévu.", "Expire dans l'eau, inspire tête tournée.",
                      ["Corps long et gainé.", "Rotation des épaules à chaque mouvement de bras."],
                      ["Lever la tête vers l'avant pour respirer.", "Battements trop amples."]),
        "boxing": t("En garde face au sac : pied avant devant, poings près du menton, genoux souples.",
                    ["Direct du bras avant, puis retour en garde.", "Direct du bras arrière en tournant la hanche, puis retour en garde.", "Enchaîne en restant en mouvement."],
                    "Bras tendu au moment de l'impact, sans verrouiller.", "Expire à chaque coup.",
                    ["Le poing revient toujours protéger le menton.", "Bandes et gants pour protéger les mains."],
                    ["Baisser la garde.", "Frapper avec le bras seul, sans les jambes."]),
        // Mobility and stretching
        "shoulder-dislocates": t("Debout, bâton tenu à deux mains en prise large devant les cuisses, bras tendus.",
                                 ["Monte le bâton au-dessus de la tête, bras tendus.", "Continue jusque derrière le dos.", "Reviens par le même chemin."],
                                 "Toute l'amplitude confortable, sans plier les coudes.", "Respire calmement.",
                                 ["Élargis la prise si ça bloque.", "Mouvement lent."],
                                 ["Plier les coudes pour passer.", "Cambrer le dos."]),
        "hip-circles": t("Debout, pieds largeur d'épaules, mains sur les hanches.",
                         ["Dessine de grands cercles avec le bassin.", "Change de sens après quelques tours."],
                         "Toute l'amplitude confortable.", "Respire calmement.",
                         ["Les épaules restent au-dessus des pieds.", "Mouvement lent."],
                         ["Bouger le buste plutôt que le bassin.", "Aller trop vite."]),
        "cat-cow": t("À quatre pattes, mains sous les épaules, genoux sous les hanches.",
                     ["Arrondis le dos et rentre la tête (chat).", "Creuse doucement le dos et regarde devant (vache).", "Alterne au rythme de la respiration."],
                     "Toute l'amplitude confortable.", "Expire en arrondissant, inspire en creusant.",
                     ["Mouvement qui part du bassin.", "Bras tendus."],
                     ["Forcer dans le creux du dos.", "Aller trop vite."]),
        "worlds-greatest": t("En fente avant, main opposée au sol à l'intérieur du pied avant.",
                             ["Amène le coude vers le pied avant.", "Ouvre le bras vers le plafond en tournant le buste.", "Reviens, puis change de côté."],
                             "Toute l'amplitude confortable.", "Expire en ouvrant.",
                             ["Genou arrière tendu ou posé.", "Regarde ta main en haut."],
                             ["Forcer la rotation.", "Laisser tomber les hanches."]),
        "ankle-mobility": t("Genou arrière au sol, face au mur, pied avant à une dizaine de centimètres du mur.",
                            ["Avance le genou avant vers le mur, au-dessus des orteils.", "Garde le talon au sol.", "Reviens, puis recule un peu le pied pour progresser."],
                            "Tant que le talon reste au sol.", "Respire calmement.",
                            ["Genou dans l'axe du pied.", "Mains au mur pour l'équilibre."],
                            ["Décoller le talon.", "Genou qui part vers l'intérieur."]),
        "thoracic-rotation": t("À quatre pattes, une main derrière la tête.",
                               ["Amène le coude vers le bras d'appui.", "Ouvre le coude vers le plafond en tournant le haut du dos.", "Reviens lentement."],
                               "Toute l'amplitude confortable.", "Expire en ouvrant.",
                               ["Le bassin reste immobile.", "Suis le coude du regard."],
                               ["Tourner le bassin.", "Aller trop vite."]),
        "deep-squat-hold": t("Debout, pieds un peu plus larges que les épaules, pointes ouvertes.",
                             ["Descends le plus bas possible, talons au sol.", "Mains jointes devant toi, coudes contre l'intérieur des genoux.", "Tiens en respirant, puis remonte."],
                             "Le plus bas confortable, talons au sol.", "Respire lentement.",
                             ["Pousse doucement les genoux vers l'extérieur avec les coudes.", "Dos le plus droit possible."],
                             ["Décoller les talons.", "Forcer dans la douleur."]),
        "hip-flexor-stretch": t("En fente, genou arrière posé au sol, pied avant devant toi.",
                                ["Avance doucement le bassin vers l'avant.", "Serre le fessier du côté du genou au sol.", "Tiens, puis change de côté."],
                                "Jusqu'à une tension agréable à l'avant de la hanche.", "Respire lentement.",
                                ["Buste droit.", "Un coussin sous le genou."],
                                ["Cambrer le bas du dos.", "Forcer jusqu'à la douleur."]),
        "childs-pose": t("À genoux, gros orteils joints, genoux écartés ou serrés.",
                         ["Assieds-toi sur les talons.", "Penche le buste vers l'avant sur les cuisses.", "Allonge les bras devant toi au sol et relâche."],
                         "Jusqu'à une détente agréable du dos.", "Respire lentement dans le dos.",
                         ["Front posé au sol.", "Épaules relâchées."],
                         ["Forcer les fesses vers les talons.", "Retenir sa respiration."]),
        "pigeon": t("Une jambe pliée devant toi, tibia au sol, l'autre jambe allongée derrière.",
                    ["Garde le bassin de face.", "Descends doucement le buste vers l'avant sur les mains.", "Tiens, puis change de côté."],
                    "Jusqu'à une tension agréable dans la fesse.", "Respire lentement.",
                    ["Un coussin sous la hanche si besoin.", "Bassin bien droit."],
                    ["Forcer sur le genou avant.", "Bassin qui bascule."]),
        "cobra": t("Allongé sur le ventre, mains au sol sous les épaules, jambes allongées.",
                   ["Pousse doucement sur les mains pour relever la poitrine.", "Garde les hanches au sol.", "Redescends lentement."],
                   "Jusqu'à une tension agréable dans le ventre, sans douleur au dos.", "Inspire en montant, expire en redescendant.",
                   ["Épaules basses, loin des oreilles.", "Coudes légèrement fléchis."],
                   ["Décoller les hanches.", "Forcer la cambrure."]),
    ]
}
