import Foundation

/// The technique of the exercises whose movement differs from the general one of their family
/// (a face pull is not a seated row, a dead bug is not a leg raise...). Written to match their
/// demonstration step by step.
extension ExerciseLibrary {
    static func technique(for id: String) -> ExerciseTechnique? { techniques[id] }

    private static func t(_ start: String, _ steps: [String], _ range: String, _ breathing: String, _ tips: [String],
                          _ mistakes: [String]) -> ExerciseTechnique {
        ExerciseTechnique(start: start, steps: steps, range: range, breathing: breathing, tips: tips, mistakes: mistakes)
    }

    private static let techniques: [String: ExerciseTechnique] = [
        // Chest and legs: variants whose setup differs from their family
        "pec-deck": t(tr("Assis sur la machine, dos plaqué contre le dossier, poignées à hauteur des épaules, bras ouverts sur les côtés, coudes légèrement fléchis."),
                      [tr("Rapproche les poignées devant la poitrine en arc de cercle."), tr("Serre les pectoraux une seconde, mains jointes."), tr("Ouvre lentement jusqu'à sentir l'étirement, sans dépasser la ligne des épaules.")],
                      tr("Des bras ouverts à la ligne des épaules jusqu'aux mains jointes devant la poitrine."), tr("Expire en fermant, inspire en ouvrant."),
                      [tr("Règle le siège pour avoir les poignées à hauteur des épaules."), tr("Garde la même flexion des coudes du début à la fin.")],
                      [tr("Décoller le dos du dossier."), tr("Pousser avec les bras en pliant les coudes."), tr("Laisser les charges claquer en ouvrant.")]),
        "cable-fly": t(tr("Debout entre les deux poulies hautes, une poignée dans chaque main, un pied en avant, buste légèrement penché, bras ouverts, coudes un peu fléchis."),
                       [tr("Amène les mains l'une vers l'autre devant le bas de la poitrine en arc de cercle."), tr("Serre les pectoraux mains jointes."), tr("Reviens lentement bras ouverts.")],
                       tr("Des bras ouverts dans la ligne des épaules aux mains jointes."), tr("Expire en fermant, inspire en ouvrant."),
                       [tr("Coudes fixes, le mouvement vient des épaules."), tr("Buste stable.")],
                       [tr("Transformer l'écarté en développé."), tr("Se laisser tirer vers l'arrière par les câbles.")]),
        "front-squat": t(tr("Debout, barre posée sur l'avant des épaules contre les clavicules, bras croisés devant (ou prise olympique), coudes hauts, pieds largeur d'épaules."),
                         [tr("Descends en gardant le buste bien droit et les coudes hauts."), tr("Genoux dans l'axe des pieds jusqu'aux cuisses parallèles."), tr("Remonte en poussant dans tout le pied.")],
                         tr("Au moins jusqu'aux cuisses parallèles, buste droit."), tr("Inspire et gaine en haut, expire en remontant."),
                         [tr("Coudes hauts pour que la barre ne glisse pas."), tr("Regard droit devant.")],
                         [tr("Coudes qui tombent."), tr("Buste qui part en avant."), tr("Talons qui décollent.")]),
        // Back and shoulders
        "dead-hang": t(tr("Suspendu à la barre, mains largeur d'épaules, bras tendus, pieds décollés du sol."),
                       [tr("Abaisse légèrement les épaules pour les engager."), tr("Tiens la suspension en respirant calmement."), tr("Repose les pieds au sol avant de lâcher.")],
                       tr("Bras tendus tout le long : on ne tire pas."), tr("Respire calmement, sans bloquer."),
                       [tr("Serre fort la barre."), tr("Gaine légèrement le ventre.")],
                       [tr("Hausser les épaules jusqu'aux oreilles."), tr("Se balancer."), tr("Lâcher la barre d'un coup.")]),
        "face-pull": t(tr("Debout face à la poulie haute, corde à hauteur des yeux, bras tendus, un pas en arrière."),
                       [tr("Tire la corde vers le visage en ouvrant les coudes, hauts et vers l'extérieur."), tr("Écarte les mains de chaque côté de la tête."), tr("Reviens bras tendus sous contrôle.")],
                       tr("Des bras tendus jusqu'aux mains à hauteur des oreilles."), tr("Expire en tirant, inspire en revenant."),
                       [tr("Coudes au niveau des épaules ou un peu au-dessus."), tr("Serre les omoplates en fin de mouvement.")],
                       [tr("Tirer avec le dos en se penchant en arrière."), tr("Coudes qui tombent le long du corps."), tr("Charge trop lourde.")]),
        "band-pull-apart": t(tr("Debout, bras tendus devant toi à hauteur des épaules, l'élastique dans les mains."),
                             [tr("Écarte les bras sur les côtés en gardant les coudes tendus."), tr("Amène l'élastique contre la poitrine."), tr("Reviens lentement bras devant.")],
                             tr("Jusqu'à l'élastique contre la poitrine, bras dans l'alignement des épaules."), tr("Expire en écartant, inspire en revenant."),
                             [tr("Serre les omoplates."), tr("Épaules basses.")],
                             [tr("Plier les coudes."), tr("Cambrer le dos."), tr("Hausser les épaules.")]),
        "rear-delt-fly": t(tr("Debout, buste penché presque à l'horizontale, dos plat, genoux fléchis, haltères sous les épaules."),
                           [tr("Ouvre les bras sur les côtés, coudes légèrement fléchis."), tr("Monte jusqu'aux bras à hauteur des épaules."), tr("Redescends lentement.")],
                           tr("Jusqu'aux bras dans l'alignement des épaules."), tr("Expire en ouvrant, inspire en redescendant."),
                           [tr("C'est l'arrière de l'épaule qui travaille : charge légère."), tr("Nuque dans l'alignement du dos.")],
                           [tr("Redresser le buste pour donner de l'élan."), tr("Tirer les coudes vers l'arrière (ça devient un rowing)."), tr("Dos rond.")]),
        "reverse-pec-deck": t(tr("Assis face à la machine, poitrine contre l'appui, bras tendus devant toi sur les poignées à hauteur des épaules."),
                              [tr("Ouvre les bras vers l'arrière en arc de cercle."), tr("Va jusqu'aux bras dans l'alignement des épaules."), tr("Reviens lentement devant.")],
                              tr("Des mains devant toi jusqu'aux bras à l'horizontale sur les côtés."), tr("Expire en ouvrant, inspire en revenant."),
                              [tr("Règle le siège : poignées à hauteur des épaules."), tr("Coudes légèrement fléchis et fixes.")],
                              [tr("Décoller la poitrine de l'appui."), tr("Hausser les épaules."), tr("Revenir trop vite.")]),
        "straight-arm-pulldown": t(tr("Debout face à la poulie haute, un pas en arrière, buste légèrement penché, bras tendus vers la barre."),
                                   [tr("Abaisse la barre en arc de cercle jusqu'aux cuisses, bras tendus."), tr("Serre le dos en bas."), tr("Remonte lentement à hauteur des yeux.")],
                                   tr("De la barre à hauteur des yeux jusqu'aux cuisses."), tr("Expire en abaissant, inspire en remontant."),
                                   [tr("Coudes légèrement fléchis et fixes."), tr("Le buste ne bouge pas.")],
                                   [tr("Plier les coudes (ça devient un triceps)."), tr("Basculer le buste pour descendre.")]),
        "pallof-press": t(tr("Debout de profil à la poulie réglée à hauteur de poitrine, poignée contre le sternum, pieds largeur d'épaules."),
                          [tr("Pousse la poignée droit devant toi jusqu'aux bras tendus."), tr("Tiens une à deux secondes sans laisser le buste tourner."), tr("Ramène la poignée contre la poitrine.")],
                          tr("De la poitrine aux bras tendus devant toi."), tr("Expire en poussant, respire calmement en tenant."),
                          [tr("Gaine le ventre et serre les fessiers."), tr("Fais les deux côtés.")],
                          [tr("Laisser le buste tourner vers la poulie."), tr("Se pencher."), tr("Charge trop lourde.")]),
        // Arms
        "wrist-curl": t(tr("Assis sur un banc, avant-bras posés sur les cuisses, poignets dans le vide, barre en main paumes vers le haut."),
                        [tr("Laisse descendre la barre en pliant les poignets."), tr("Remonte en fléchissant les poignets le plus haut possible."), tr("Redescends lentement.")],
                        tr("Seuls les poignets bougent, toute l'amplitude confortable."), tr("Expire en montant, inspire en redescendant."),
                        [tr("Avant-bras bien posés."), tr("Charge légère, mouvement lent.")],
                        [tr("Décoller les avant-bras."), tr("Donner de l'élan avec les épaules.")]),
        "concentration-curl": t(tr("Assis au bout d'un banc, jambes écartées, buste penché, l'arrière du bras contre l'intérieur de la cuisse."),
                                [tr("Plie le coude pour monter l'haltère vers l'épaule."), tr("Serre en haut."), tr("Redescends lentement jusqu'au bras tendu.")],
                                tr("Du bras tendu jusqu'à la flexion complète."), tr("Expire en montant, inspire en redescendant."),
                                [tr("Le bras reste collé à la cuisse."), tr("L'autre main en appui sur l'autre cuisse.")],
                                [tr("Bouger le buste."), tr("Décoller le coude de la cuisse.")]),
        "kickback": t(tr("Debout, buste penché presque à l'horizontale, dos plat, bras collés au corps, coudes pliés à 90°."),
                      [tr("Tends les avant-bras vers l'arrière jusqu'aux bras tendus."), tr("Marque une seconde."), tr("Reviens lentement à 90°.")],
                      tr("Du coude plié à 90° jusqu'au bras tendu."), tr("Expire en tendant, inspire en revenant."),
                      [tr("Le haut du bras reste immobile, le long du buste."), tr("Charge légère.")],
                      [tr("Coude qui descend."), tr("Balancer la charge."), tr("Dos rond.")]),
        "overhead-extension": t(tr("Debout, un haltère tenu à deux mains au-dessus de la tête, bras tendus."),
                                [tr("Plie les coudes pour descendre l'haltère derrière la tête."), tr("Tends de nouveau les bras.")],
                                tr("Tant que les épaules restent confortables."), tr("Inspire en descendant, expire en tendant."),
                                [tr("Coudes pointés vers le haut, proches de la tête."), tr("Gaine le ventre pour ne pas cambrer.")],
                                [tr("Coudes qui s'écartent."), tr("Cambrer le dos.")]),
        "bench-dips": t(tr("Dos au banc, mains sur le bord, doigts vers l'avant, jambes allongées, talons au sol."),
                        [tr("Plie les coudes pour descendre les fesses le long du banc."), tr("Pousse sur les mains pour remonter bras tendus.")],
                        tr("Jusqu'aux coudes à environ 90°."), tr("Inspire en descendant, expire en remontant."),
                        [tr("Fesses près du banc."), tr("Coudes vers l'arrière, pas sur les côtés.")],
                        [tr("Descendre trop bas."), tr("Épaules qui montent vers les oreilles.")]),
        // Legs and glutes
        "wall-sit": t(tr("Dos plaqué au mur, pieds en avant, écartés largeur de hanches."),
                      [tr("Glisse le long du mur jusqu'aux cuisses parallèles au sol."), tr("Genoux au-dessus des chevilles : tiens la position."), tr("Remonte en glissant contre le mur.")],
                      tr("Cuisses parallèles au sol, position fixe."), tr("Respire calmement, sans bloquer."),
                      [tr("Tout le dos contre le mur."), tr("Poids sur les talons.")],
                      [tr("Genoux qui dépassent les orteils."), tr("Mains sur les cuisses pour s'aider.")]),
        "hack-squat": t(tr("Dos et épaules contre les appuis de la machine, pieds largeur d'épaules sur le plateau."),
                        [tr("Déverrouille les sécurités."), tr("Descends en pliant les genoux, le dos glisse le long des rails."), tr("Pousse dans tout le pied pour remonter.")],
                        tr("Jusqu'aux cuisses parallèles au plateau."), tr("Inspire en descendant, expire en poussant."),
                        [tr("Genoux dans l'axe des pieds."), tr("Bas du dos collé au dossier.")],
                        [tr("Verrouiller les genoux en haut."), tr("Talons qui décollent."), tr("Genoux qui rentrent.")]),
        "step-up": t(tr("Debout face au banc, haltères le long du corps, un pied posé à plat sur le banc."),
                     [tr("Pousse sur la jambe posée sur le banc pour monter."), tr("Ramène l'autre pied à côté, debout sur le banc."), tr("Redescends sous contrôle, un pied après l'autre.")],
                     tr("Du pied au sol jusqu'à debout sur le banc."), tr("Expire en montant, inspire en descendant."),
                     [tr("Pose tout le pied sur le banc."), tr("Buste droit.")],
                     [tr("Pousser avec la jambe restée au sol."), tr("Genou qui rentre.")]),
        "nordic-curl": t(tr("À genoux sur un tapis, chevilles bloquées sous un appui, corps droit des genoux à la tête."),
                         [tr("Descends le buste vers l'avant le plus lentement possible, hanches tendues."), tr("Amortis avec les mains près du sol."), tr("Repousse légèrement et remonte.")],
                         tr("Aussi bas que tu peux contrôler la descente."), tr("Inspire en descendant, expire en remontant."),
                         [tr("Hanches dans l'alignement : on ne casse pas au bassin."), tr("Progresse petit à petit.")],
                         [tr("Plier les hanches."), tr("Se laisser tomber.")]),
        "single-leg-rdl": t(tr("Debout sur une jambe, genou légèrement fléchi, haltère dans la main opposée."),
                            [tr("Penche le buste en avant pendant que la jambe libre part vers l'arrière."), tr("Descends jusqu'au corps à l'horizontale, en « T »."), tr("Reviens debout en poussant la hanche vers l'avant.")],
                            tr("Jusqu'au buste presque horizontal, dos plat."), tr("Inspire en descendant, expire en remontant."),
                            [tr("Bassin face au sol."), tr("Charge près de la jambe d'appui.")],
                            [tr("Ouvrir la hanche sur le côté."), tr("Dos rond.")]),
        "kb-swing": t(tr("Debout, pieds un peu plus larges que les hanches, kettlebell au sol devant toi."),
                      [tr("Charnière de hanches : la kettlebell passe entre les jambes."), tr("Pousse les hanches vers l'avant d'un coup sec."), tr("La kettlebell monte à hauteur de poitrine, bras tendus, puis redescend en balancier.")],
                      tr("Bras à l'horizontale en haut."), tr("Expire au coup de hanches."),
                      [tr("La force vient des hanches, les bras ne font que tenir."), tr("Serre les fessiers en haut.")],
                      [tr("Squatter au lieu de plier les hanches."), tr("Lever la kettlebell avec les bras."), tr("Dos rond en bas.")]),
        "glute-bridge": t(tr("Allongé sur le dos, genoux pliés, pieds à plat largeur de hanches, bras le long du corps."),
                          [tr("Pousse dans les talons pour monter les hanches."), tr("Serre les fessiers en haut, épaules-hanches-genoux alignés."), tr("Redescends sous contrôle.")],
                          tr("Jusqu'à l'alignement du buste et des cuisses."), tr("Expire en montant, inspire en redescendant."),
                          [tr("Menton rentré."), tr("Pieds pas trop loin des fesses.")],
                          [tr("Cambrer le bas du dos en haut."), tr("Pousser sur la pointe des pieds.")]),
        "single-leg-bridge": t(tr("Allongé sur le dos, un pied à plat, l'autre jambe tendue dans l'alignement de la cuisse."),
                               [tr("Pousse dans le talon d'appui pour monter les hanches."), tr("Garde le bassin de niveau en haut."), tr("Redescends sous contrôle.")],
                               tr("Jusqu'à l'alignement épaules-hanches-genou."), tr("Expire en montant, inspire en redescendant."),
                               [tr("Bassin bien horizontal."), tr("Fais les deux côtés.")],
                               [tr("Bassin qui bascule d'un côté."), tr("Cambrer le dos.")]),
        "donkey-kick": t(tr("À quatre pattes, mains sous les épaules, genoux sous les hanches, dos plat."),
                         [tr("Genou plié à 90°, pousse le talon vers le plafond."), tr("Monte jusqu'à la cuisse dans l'alignement du dos."), tr("Reviens sans poser le genou.")],
                         tr("Jusqu'à la cuisse à l'horizontale."), tr("Expire en montant, inspire en revenant."),
                         [tr("Le bassin reste face au sol."), tr("Ventre gainé.")],
                         [tr("Cambrer pour monter plus haut."), tr("Tourner le bassin.")]),
        "fire-hydrant": t(tr("À quatre pattes, mains sous les épaules, genoux sous les hanches, dos plat."),
                          [tr("Lève le genou plié sur le côté."), tr("Monte jusqu'à la cuisse presque horizontale."), tr("Redescends lentement.")],
                          tr("Tant que le bassin ne tourne pas."), tr("Expire en levant, inspire en redescendant."),
                          [tr("Genou plié à 90° tout le long."), tr("Épaules et bassin immobiles.")],
                          [tr("Pencher tout le corps de l'autre côté."), tr("Aller trop vite.")]),
        "cable-kickback": t(tr("Debout face à la poulie basse, sangle à la cheville, mains sur la machine, buste légèrement penché."),
                            [tr("Pousse la jambe tendue vers l'arrière en contractant le fessier."), tr("Marque une seconde."), tr("Reviens lentement.")],
                            tr("Jusqu'à la jambe un peu derrière le corps, sans cambrer."), tr("Expire en poussant, inspire en revenant."),
                            [tr("Le bassin reste immobile."), tr("Genou presque tendu.")],
                            [tr("Cambrer le bas du dos."), tr("Balancer la jambe.")]),
        "hip-abduction": t(tr("Assis dans la machine, dos contre le dossier, coussins contre l'extérieur des genoux."),
                           [tr("Écarte les genoux contre la résistance."), tr("Marque une seconde en ouverture."), tr("Reviens lentement.")],
                           tr("Toute l'amplitude confortable."), tr("Expire en écartant, inspire en revenant."),
                           [tr("Tiens les poignées pour rester assis."), tr("Mouvement lent.")],
                           [tr("Laisser claquer les charges."), tr("Décoller le dos.")]),
        "hip-adduction": t(tr("Assis dans la machine, dos contre le dossier, coussins contre l'intérieur des genoux, jambes écartées."),
                           [tr("Resserre les genoux contre la résistance."), tr("Marque une seconde genoux joints."), tr("Rouvre lentement.")],
                           tr("De l'ouverture confortable jusqu'aux genoux joints."), tr("Expire en serrant, inspire en ouvrant."),
                           [tr("Tiens les poignées."), tr("Ouverture sans forcer.")],
                           [tr("Ouvrir trop grand."), tr("Donner de l'élan.")]),
        "seated-calf": t(tr("Assis à la machine, coussin sur le bas des cuisses, avant des pieds sur la marche."),
                         [tr("Laisse descendre les talons sous la marche."), tr("Monte sur la pointe des pieds le plus haut possible."), tr("Redescends lentement.")],
                         tr("Du talon bas jusqu'à la pointe haute."), tr("Expire en montant, inspire en redescendant."),
                         [tr("Pause en bas et en haut."), tr("Genoux à 90°.")],
                         ["Rebondir.", tr("Amplitude trop courte.")]),
        "single-calf": t(tr("Debout sur une jambe, l'avant du pied sur une marche, haltère du même côté, l'autre main contre un mur."),
                         [tr("Laisse descendre le talon sous la marche."), tr("Monte sur la pointe du pied le plus haut possible."), tr("Redescends lentement.")],
                         tr("Du talon bas jusqu'à la pointe haute."), tr("Expire en montant, inspire en redescendant."),
                         [tr("Jambe d'appui droite sans verrouiller."), tr("La main ne sert qu'à l'équilibre.")],
                         ["Rebondir.", tr("Pousser avec la main sur le mur.")]),
        // Core
        "cable-crunch": t(tr("À genoux face à la poulie haute, la corde tenue de chaque côté de la tête."),
                          [tr("Enroule le buste vers le sol, coudes vers les cuisses."), tr("Les hanches restent immobiles."), tr("Remonte lentement.")],
                          tr("Jusqu'aux coudes près des cuisses."), tr("Expire en enroulant, inspire en remontant."),
                          [tr("Ce sont les abdominaux qui tirent, pas les bras."), tr("Dos qui s'arrondit, hanches fixes.")],
                          [tr("S'asseoir sur les talons pour descendre."), tr("Tirer avec les bras.")]),
        "side-plank": t(tr("Allongé sur le côté, avant-bras au sol, coude sous l'épaule, jambes tendues l'une sur l'autre."),
                        [tr("Monte les hanches jusqu'à aligner tout le corps."), tr("Tiens la position."), tr("Redescends doucement, puis change de côté.")],
                        tr("Corps aligné des chevilles à la tête, position fixe."), tr("Respire calmement, sans bloquer."),
                        [tr("Hanches hautes, ne les laisse pas tomber."), tr("Épaule au-dessus du coude.")],
                        [tr("Hanches qui s'affaissent."), tr("Buste qui bascule vers l'avant.")]),
        "ab-wheel": t(tr("À genoux, mains sur la roue sous les épaules, dos neutre."),
                      [tr("Roule vers l'avant en allongeant le corps."), tr("Va aussi loin que tu tiens le dos neutre."), tr("Reviens en contractant les abdominaux.")],
                      tr("Tant que le bas du dos ne se creuse pas."), tr("Inspire en avançant, expire en revenant."),
                      [tr("Fessiers et ventre serrés."), tr("Progresse en amplitude petit à petit.")],
                      [tr("Creuser le dos."), tr("Revenir en poussant les fesses vers l'arrière en premier.")]),
        "dead-bug": t(tr("Allongé sur le dos, bras tendus vers le plafond, hanches et genoux pliés à 90°."),
                      [tr("Tends un bras derrière la tête et la jambe opposée près du sol."), tr("Reviens au centre."), tr("Change de côté.")],
                      tr("Tant que le bas du dos reste plaqué au sol."), tr("Expire en tendant, inspire en revenant."),
                      [tr("Bas du dos collé au sol tout le long."), tr("Mouvement lent.")],
                      [tr("Creuser le dos."), tr("Bouger le bras et la jambe du même côté.")]),
        "hollow-hold": t(tr("Allongé sur le dos, bras tendus derrière la tête, jambes tendues."),
                         [tr("Décolle les épaules, les bras et les jambes du sol."), tr("Bas du dos plaqué : tiens la position en « banane »."), tr("Repose doucement.")],
                         tr("Bras et jambes juste au-dessus du sol, position fixe."), tr("Respire calmement, sans bloquer."),
                         [tr("Plus les jambes sont hautes, plus c'est facile."), tr("Menton rentré.")],
                         [tr("Creuser le bas du dos."), tr("Retenir sa respiration.")]),
        "back-extension": t(tr("Sur le banc à 45°, hanches sur l'appui, chevilles bloquées sous les rouleaux, corps aligné, bras croisés."),
                            [tr("Descends le buste vers le sol en pliant les hanches."), tr("Remonte jusqu'à l'alignement du corps."), tr("Pas plus haut.")],
                            tr("Du buste vers le sol jusqu'au corps aligné, sans cambrer."), tr("Inspire en descendant, expire en remontant."),
                            [tr("Dos plat tout le long."), tr("Serre les fessiers en remontant.")],
                            [tr("Cambrer en haut."), tr("Donner de l'élan.")]),
        "bird-dog": t(tr("À quatre pattes, mains sous les épaules, genoux sous les hanches, dos plat."),
                      [tr("Tends un bras devant toi et la jambe opposée derrière."), tr("Tiens une seconde, le dos immobile."), tr("Reviens et change de côté.")],
                      tr("Bras et jambe dans l'alignement du dos."), tr("Expire en tendant, inspire en revenant."),
                      [tr("Bassin face au sol."), tr("Mouvement lent.")],
                      [tr("Cambrer le dos."), tr("Lever la jambe trop haut.")]),
        // Full body and cardio
        "burpee": t(tr("Debout, pieds largeur de hanches."),
                    [tr("Accroupis-toi et pose les mains au sol."), tr("Saute les pieds en arrière en planche."), tr("Ramène les pieds sous toi d'un saut."), tr("Saute vers le haut, bras au-dessus de la tête, et reçois-toi souplement.")],
                    tr("Enchaîne à ton rythme, corps gainé en planche."), tr("Respire en rythme."),
                    [tr("Mains à plat sous les épaules en planche."), tr("Réception sur l'avant du pied, genoux fléchis.")],
                    [tr("Hanches qui s'affaissent en planche."), tr("Atterrir jambes tendues.")]),
        "thruster": t(tr("Debout, barre en position de squat avant, coudes hauts."),
                      [tr("Descends en squat avant, buste droit."), tr("Remonte de façon explosive et pousse la barre au-dessus de la tête dans le même élan."), tr("Ramène la barre aux épaules en descendant dans le squat suivant.")],
                      tr("Du squat aux bras tendus au-dessus de la tête."), tr("Inspire en descendant, expire en poussant."),
                      [tr("La poussée des jambes lance la barre."), tr("Barre au-dessus du milieu du pied.")],
                      [tr("Pousser avec les bras seuls."), tr("Coudes qui tombent en bas du squat.")]),
        "power-clean": t(tr("Barre au sol au-dessus du milieu du pied, dos plat, bras tendus, épaules légèrement devant la barre."),
                         [tr("Premier tirage : pousse avec les jambes, barre collée aux tibias."), tr("Extension explosive des hanches, sur la pointe des pieds, haussement d'épaules."), tr("Passe sous la barre : réception sur l'avant des épaules en squat partiel, coudes hauts."), tr("Redresse-toi, puis redescends la barre aux hanches et au sol.")],
                         tr("Du sol aux épaules."), tr("Bloque l'air au départ, expire après la réception."),
                         [tr("La barre reste près du corps."), tr("Apprends-le avec un coach, à vide d'abord.")],
                         [tr("Tirer avec les bras trop tôt."), tr("Dos rond au départ."), tr("Recevoir la barre bras tendus devant.")]),
        "kb-clean": t(tr("Debout, kettlebell entre les pieds, saisie d'une main."),
                      [tr("Balancier entre les jambes, puis coup de hanches."), tr("La kettlebell monte près du corps."), tr("Elle se pose sur l'avant-bras, coude collé au buste, main à hauteur du menton."), tr("Redescends-la en balancier.")],
                      tr("Des jambes jusqu'à la position de rack."), tr("Expire au coup de hanches."),
                      [tr("Tourne la main autour de la poignée pour amortir."), tr("Coude serré au corps en haut.")],
                      [tr("Laisser la kettlebell frapper l'avant-bras."), tr("Tirer avec le bras seul.")]),
        "turkish-get-up": t(tr("Allongé sur le dos, kettlebell bras tendu vers le plafond, genou du même côté plié, pied au sol."),
                            [tr("Monte sur le coude opposé, puis sur la main."), tr("Lève les hanches."), tr("Passe la jambe tendue sous toi pour poser le genou."), tr("Redresse le buste, puis lève-toi ; redescends dans l'ordre inverse.")],
                            tr("Du sol à debout, bras toujours tendu vers le plafond."), tr("Respire à chaque étape."),
                            [tr("Regarde la kettlebell."), tr("Commence sans charge pour apprendre les étapes.")],
                            [tr("Plier le bras qui tient la charge."), tr("Aller trop vite."), tr("Charger avant de maîtriser.")]),
        "wall-ball": t(tr("Debout face au mur à un pas, médecine-ball tenu contre la poitrine."),
                       [tr("Descends en squat."), tr("Remonte en poussant et lance le ballon vers la cible."), tr("Rattrape-le et enchaîne le squat suivant.")],
                       tr("Squat complet, bras tendus au lancer."), tr("Expire au lancer."),
                       [tr("Les jambes donnent la force du lancer."), tr("Coudes sous le ballon.")],
                       [tr("Lancer seulement avec les bras."), tr("Rattraper le ballon bras tendus et dos cambré.")]),
        "battle-ropes": t(tr("Debout face à l'ancrage, genoux fléchis, buste légèrement penché, une corde dans chaque main."),
                          [tr("Lève et abaisse les bras en alternance."), tr("Fais onduler les cordes jusqu'à l'ancrage."), tr("Garde le rythme sur la durée prévue.")],
                          tr("Mouvements amples des bras, des hanches à la poitrine."), tr("Respire en rythme."),
                          [tr("Gaine le ventre."), tr("Reste bas sur les jambes.")],
                          [tr("Se redresser complètement."), tr("Bloquer sa respiration.")]),
        "sled-push": t(tr("Mains sur les montants du traîneau, bras tendus, buste penché vers l'avant."),
                       [tr("Pousse le sol avec les jambes, à petits pas puissants."), tr("Garde le dos droit et le buste penché."), tr("Avance sur la distance prévue.")],
                       tr("Sur la distance ou le temps choisi."), tr("Respire en rythme."),
                       [tr("Pousse avec l'avant du pied."), tr("Bras tendus et fixes.")],
                       [tr("Dos rond."), tr("Se redresser en poussant.")]),
        "bear-crawl": t(tr("À quatre pattes, mains sous les épaules, genoux juste au-dessus du sol."),
                        [tr("Avance une main et le pied opposé en même temps."), tr("Puis l'autre main et l'autre pied."), tr("Garde les genoux bas et le dos plat.")],
                        tr("Sur la distance ou le temps choisi."), tr("Respire en rythme."),
                        [tr("Hanches à la hauteur des épaules."), tr("Petits pas.")],
                        [tr("Hanches trop hautes."), tr("Genoux qui touchent le sol.")]),
        "treadmill": t(tr("Debout au milieu du tapis, regard devant, sans tenir les barres."),
                       [tr("Démarre doucement, puis règle la vitesse."), tr("Cours avec une foulée souple, sous le corps."), tr("Ralentis progressivement avant de t'arrêter.")],
                       tr("Sur la durée ou la distance prévue."), tr("Respire régulièrement."),
                       [tr("Reste au centre du tapis."), tr("Bras détendus, coudes à 90°.")],
                       [tr("S'accrocher aux barres."), tr("Monter trop vite en vitesse.")]),
        "incline-walk": t(tr("Debout sur le tapis réglé en pente, regard devant."),
                          [tr("Marche à grands pas réguliers."), tr("Pose le pied à plat et pousse jusqu'aux orteils."), tr("Ajuste la pente et la vitesse selon la séance.")],
                          tr("Sur la durée prévue."), tr("Respire régulièrement ; tu dois pouvoir parler."),
                          [tr("Buste légèrement penché, pas plus."), tr("Sans tenir les barres si possible.")],
                          [tr("S'accrocher aux barres."), tr("Pente trop forte dès le départ.")]),
        "high-knees": t(tr("Debout, pieds largeur de hanches, bras pliés."),
                        [tr("Monte un genou à hauteur de hanche."), tr("Change de jambe rapidement, sur place."), tr("Les bras accompagnent en rythme.")],
                        tr("Genoux à hauteur de hanches."), tr("Respire en rythme."),
                        [tr("Réception sur l'avant du pied."), tr("Buste droit.")],
                        [tr("Se pencher en arrière."), tr("Genoux trop bas.")]),
        "elliptical": t(tr("Debout sur les pédales, mains sur les poignées mobiles, buste droit."),
                        [tr("Pédale en mouvement elliptique, pieds à plat."), tr("Pousse et tire les poignées en rythme avec les jambes."), tr("Ajuste la résistance selon la séance.")],
                        tr("Sur la durée prévue."), tr("Respire régulièrement."),
                        [tr("Talons qui restent sur les pédales."), tr("Buste droit, sans s'appuyer.")],
                        [tr("Se pencher sur la console."), tr("Résistance trop forte.")]),
        "stair-climber": t(tr("Debout sur les pédales du stepper, mains légèrement posées sur les barres."),
                           [tr("Pousse une pédale vers le bas pendant que l'autre remonte."), tr("Alterne à rythme régulier."), tr("Garde le buste droit.")],
                           tr("Sur la durée prévue, amplitude complète."), tr("Respire régulièrement."),
                           [tr("Pose tout le pied sur la pédale."), tr("Les mains servent à l'équilibre.")],
                           [tr("S'appuyer de tout son poids sur les barres."), tr("Petits pas rapides sans amplitude.")]),
        "jump-rope": t(tr("Debout, corde derrière toi, mains à hauteur des hanches, coudes près du corps."),
                       [tr("Fais tourner la corde avec les poignets."), tr("Saute juste assez haut pour la laisser passer."), tr("Enchaîne à rythme régulier.")],
                       tr("Petits sauts sur l'avant du pied."), tr("Respire en rythme."),
                       [tr("Poignets qui tournent, pas les bras."), tr("Atterrissage souple.")],
                       [tr("Sauter trop haut."), tr("Atterrir sur les talons.")]),
        "jumping-jacks": t(tr("Debout, pieds joints, bras le long du corps."),
                           [tr("Saute en écartant les pieds et lève les bras au-dessus de la tête."), tr("Saute pour revenir pieds joints, bras le long du corps."), tr("Enchaîne à ton rythme.")],
                           tr("Bras au-dessus de la tête, pieds plus larges que les épaules."), tr("Respire en rythme."),
                           [tr("Réception sur l'avant du pied."), tr("Genoux souples.")],
                           [tr("Atterrir jambes tendues."), tr("Arrondir le dos.")]),
        "box-jump": t(tr("Debout face à la boîte, à environ un pas, pieds largeur de hanches."),
                      [tr("Élan : fléchis les jambes, bras en arrière."), tr("Saute en lançant les bras vers l'avant."), tr("Reçois-toi à deux pieds sur la boîte, genoux fléchis, puis redresse-toi."), tr("Redescends en marchant.")],
                      tr("Hauteur de boîte maîtrisée."), tr("Expire au saut."),
                      [tr("Atterrissage silencieux, au centre de la boîte."), tr("Commence avec une boîte basse.")],
                      [tr("Redescendre en sautant en arrière."), tr("Genoux qui rentrent à la réception.")]),
        "hiit": t(tr("Debout, échauffé, espace dégagé autour de toi."),
                  [tr("Enchaîne les exercices du circuit à intensité élevée (ici jumping jacks, squats sautés, montées de genoux)."), tr("Récupère entre les blocs selon ta séance."), tr("Répète le circuit.")],
                  tr("Sur les durées d'effort et de repos prévues."), tr("Respire en rythme, sans bloquer."),
                  [tr("La qualité des mouvements avant la vitesse."), tr("Adapte l'intensité à ton niveau.")],
                  [tr("Négliger l'échauffement."), tr("Sacrifier la technique en fin de série.")]),
        "swimming": t(tr("Allongé sur l'eau sur le ventre, corps aligné, visage dans l'eau."),
                      [tr("Les bras alternent : l'un tire sous l'eau pendant que l'autre revient au-dessus."), tr("Les jambes battent en petits mouvements rapides."), tr("Tourne la tête sur le côté pour respirer.")],
                      tr("Sur la distance ou le temps prévu."), tr("Expire dans l'eau, inspire tête tournée."),
                      [tr("Corps long et gainé."), tr("Rotation des épaules à chaque mouvement de bras.")],
                      [tr("Lever la tête vers l'avant pour respirer."), tr("Battements trop amples.")]),
        "boxing": t(tr("En garde face au sac : pied avant devant, poings près du menton, genoux souples."),
                    [tr("Direct du bras avant, puis retour en garde."), tr("Direct du bras arrière en tournant la hanche, puis retour en garde."), tr("Enchaîne en restant en mouvement.")],
                    tr("Bras tendu au moment de l'impact, sans verrouiller."), tr("Expire à chaque coup."),
                    [tr("Le poing revient toujours protéger le menton."), tr("Bandes et gants pour protéger les mains.")],
                    [tr("Baisser la garde."), tr("Frapper avec le bras seul, sans les jambes.")]),
        // Mobility and stretching
        "shoulder-dislocates": t(tr("Debout, bâton tenu à deux mains en prise large devant les cuisses, bras tendus."),
                                 [tr("Monte le bâton au-dessus de la tête, bras tendus."), tr("Continue jusque derrière le dos."), tr("Reviens par le même chemin.")],
                                 tr("Toute l'amplitude confortable, sans plier les coudes."), tr("Respire calmement."),
                                 [tr("Élargis la prise si ça bloque."), tr("Mouvement lent.")],
                                 [tr("Plier les coudes pour passer."), tr("Cambrer le dos.")]),
        "hip-circles": t(tr("Debout, pieds largeur d'épaules, mains sur les hanches."),
                         [tr("Dessine de grands cercles avec le bassin."), tr("Change de sens après quelques tours.")],
                         tr("Toute l'amplitude confortable."), tr("Respire calmement."),
                         [tr("Les épaules restent au-dessus des pieds."), tr("Mouvement lent.")],
                         [tr("Bouger le buste plutôt que le bassin."), tr("Aller trop vite.")]),
        "cat-cow": t(tr("À quatre pattes, mains sous les épaules, genoux sous les hanches."),
                     [tr("Arrondis le dos et rentre la tête (chat)."), tr("Creuse doucement le dos et regarde devant (vache)."), tr("Alterne au rythme de la respiration.")],
                     tr("Toute l'amplitude confortable."), tr("Expire en arrondissant, inspire en creusant."),
                     [tr("Mouvement qui part du bassin."), tr("Bras tendus.")],
                     [tr("Forcer dans le creux du dos."), tr("Aller trop vite.")]),
        "worlds-greatest": t(tr("En fente avant, main opposée au sol à l'intérieur du pied avant."),
                             [tr("Amène le coude vers le pied avant."), tr("Ouvre le bras vers le plafond en tournant le buste."), tr("Reviens, puis change de côté.")],
                             tr("Toute l'amplitude confortable."), tr("Expire en ouvrant."),
                             [tr("Genou arrière tendu ou posé."), tr("Regarde ta main en haut.")],
                             [tr("Forcer la rotation."), tr("Laisser tomber les hanches.")]),
        "ankle-mobility": t(tr("Genou arrière au sol, face au mur, pied avant à une dizaine de centimètres du mur."),
                            [tr("Avance le genou avant vers le mur, au-dessus des orteils."), tr("Garde le talon au sol."), tr("Reviens, puis recule un peu le pied pour progresser.")],
                            tr("Tant que le talon reste au sol."), tr("Respire calmement."),
                            [tr("Genou dans l'axe du pied."), tr("Mains au mur pour l'équilibre.")],
                            [tr("Décoller le talon."), tr("Genou qui part vers l'intérieur.")]),
        "thoracic-rotation": t(tr("À quatre pattes, une main derrière la tête."),
                               [tr("Amène le coude vers le bras d'appui."), tr("Ouvre le coude vers le plafond en tournant le haut du dos."), tr("Reviens lentement.")],
                               tr("Toute l'amplitude confortable."), tr("Expire en ouvrant."),
                               [tr("Le bassin reste immobile."), tr("Suis le coude du regard.")],
                               [tr("Tourner le bassin."), tr("Aller trop vite.")]),
        "deep-squat-hold": t(tr("Debout, pieds un peu plus larges que les épaules, pointes ouvertes."),
                             [tr("Descends le plus bas possible, talons au sol."), tr("Mains jointes devant toi, coudes contre l'intérieur des genoux."), tr("Tiens en respirant, puis remonte.")],
                             tr("Le plus bas confortable, talons au sol."), tr("Respire lentement."),
                             [tr("Pousse doucement les genoux vers l'extérieur avec les coudes."), tr("Dos le plus droit possible.")],
                             [tr("Décoller les talons."), tr("Forcer dans la douleur.")]),
        "hip-flexor-stretch": t(tr("En fente, genou arrière posé au sol, pied avant devant toi."),
                                [tr("Avance doucement le bassin vers l'avant."), tr("Serre le fessier du côté du genou au sol."), tr("Tiens, puis change de côté.")],
                                tr("Jusqu'à une tension agréable à l'avant de la hanche."), tr("Respire lentement."),
                                [tr("Buste droit."), tr("Un coussin sous le genou.")],
                                [tr("Cambrer le bas du dos."), tr("Forcer jusqu'à la douleur.")]),
        "childs-pose": t(tr("À genoux, gros orteils joints, genoux écartés ou serrés."),
                         [tr("Assieds-toi sur les talons."), tr("Penche le buste vers l'avant sur les cuisses."), tr("Allonge les bras devant toi au sol et relâche.")],
                         tr("Jusqu'à une détente agréable du dos."), tr("Respire lentement dans le dos."),
                         [tr("Front posé au sol."), tr("Épaules relâchées.")],
                         [tr("Forcer les fesses vers les talons."), tr("Retenir sa respiration.")]),
        "pigeon": t(tr("Une jambe pliée devant toi, tibia au sol, l'autre jambe allongée derrière."),
                    [tr("Garde le bassin de face."), tr("Descends doucement le buste vers l'avant sur les mains."), tr("Tiens, puis change de côté.")],
                    tr("Jusqu'à une tension agréable dans la fesse."), tr("Respire lentement."),
                    [tr("Un coussin sous la hanche si besoin."), tr("Bassin bien droit.")],
                    [tr("Forcer sur le genou avant."), tr("Bassin qui bascule.")]),
        "cobra": t(tr("Allongé sur le ventre, mains au sol sous les épaules, jambes allongées."),
                   [tr("Pousse doucement sur les mains pour relever la poitrine."), tr("Garde les hanches au sol."), tr("Redescends lentement.")],
                   tr("Jusqu'à une tension agréable dans le ventre, sans douleur au dos."), tr("Inspire en montant, expire en redescendant."),
                   [tr("Épaules basses, loin des oreilles."), tr("Coudes légèrement fléchis.")],
                   [tr("Décoller les hanches."), tr("Forcer la cambrure.")]),
    ]
}
